### ISSUE TITLE
Pure black Notification toast after installing

### ISSUE THREAD

**Issue by OutsideFate** [CrazyBytesVE/36-DPI-NavBar-Mod#1]
Hello CrazyBytesVE!
I just found your module, and it's everything I ever wanted, but unfortunately, it comes with a huge side effect, and that is that all notification toasts are pure black after installing the module. I've tested it, and the issue goes away after disabling your module and rebooting.

MIUI Global 13.0.9, Redmi Note 11 Pro 5G.

**Comment by OutsideFate** [comment]
I've found another issue: When you switch between light and dark themes, the module breaks and it returns to the default navigation bar. Turning it on and off doesn't fix this issue unless you switch to the theme that you installed the module on originally

**Comment by CrazyBytesVE** [comment]
> Hola CrazyBytesVE! Acabo de encontrar su módulo, y es todo lo que siempre quise, pero desafortunadamente, viene con un gran efecto secundario, y es que todas las notificaciones son de color negro puro después de instalar el módulo. Lo he probado, y el problema desaparece después de deshabilitar su módulo y reiniciar.
> 
> MIUI Global 13.0.9, Redmi Note 11 Pro 5G.

In that case, I don't know how to help you because I haven't used Miui for a long time. I'm sorry I can't help you in that aspect. I can inquire but when I'm off work.

**Comment by OutsideFate** [comment]
Hello again! I've poked into it a little further, and I've noticed the notification toast isn't pure black, as you can just about see the text on a bright white background. I think that the module, for some reason, uses dark theme notification toasts, but with light theme font, making it black on near black. I think a few lines of very dirty "force light theme notification toast" hard code might "fix" that aspect pretty easily
